Repository Raretech-Hackathon-TeamC/KotukotuProject, pull requests merged in 2023-05, with the labels that each got.

#7 add ajax view in activity app
  django/activity/urls.py
  django/activity/views.py
  django/templates/test_activity_list.html
  django/templates/test_home.html
  volumes/data/db/#innodb_redo/#ib_redo10
Labels: backend

#14 積み上げ記録追加時にカテゴリー選択機能の追加
  django/activity/forms.py
  django/activity/urls.py
  django/activity/views.py
  django/categories/views.py
  django/static/admin/js/activity_add.js
  django/templates/activity_add.html
  django/templates/test_activity_add.html
  django/templates/test_activity_edit.html
  django/templates/test_activity_list.html
  django/templates/test_category_add.html
  django/templates/test_cateogry_edit.html
  django/templates/test_home.html
  volumes/data/db/#innodb_redo/#ib_redo10
Labels: backend

#25 使用htmlファイルを本番環境用へ変更
  django/activity/views.py
  django/categories/views.py
Labels: backend

#29 ログイン、サインアップの修正
  django/kotukotupj/settings.py
  django/templates/login.html
  django/templates/regist.html
Labels: front

#27 [カテゴリー機能]カテゴリー毎のホームページ作成(category_home)
  django/categories/urls.py
  django/categories/views.py
  django/templates/category_detail.html
Labels: backend

#32 ‘各htmlファイルのinclude調整など’
  django/static/admin/js/activity_list.js
  django/static/admin/js/home.js
  django/static/admin/js/menu_modal.js
  django/staticfiles/admin/js/category_add.js
  django/staticfiles/admin/js/menu_modal.js
  django/templates/activity_add.html
  django/templates/activity_list.html
  django/templates/base.html
  django/templates/category_add.html
  django/templates/home.html
  nginx/static/admin/js/category_add.js
Labels: front

#36 [ホーム画面]見える化機能をカテゴリー毎に色分け
  django/activity/views.py
  django/templates/test_home.html
  volumes/data/db/#innodb_redo/#ib_redo10
Labels: backend

#44 ホーム画面をバックエンドと連携
  django/categories/models.py
  django/static/admin/js/categories_list.js
  django/static/admin/js/graph.js
  django/templates/home.html
Labels: front

#49 ‘activity_listの連携’
  django/activity/views.py
  django/static/admin/js/activity_list.js
  django/templates/activity_list.html
Labels: front

#54 category_detail.htmlの作成
  django/activity/views.py
  django/static/admin/js/categories_list.js
  django/static/admin/js/category_detail.js
  django/templates/base.html
  django/templates/category_detail.html
Labels: front

#61 実績機能の追加
  django/badges/__init__.py
  django/badges/admin.py
  django/badges/apps.py
  django/badges/migrations/0001_initial.py
  django/badges/migrations/__init__.py
  django/badges/models.py
  django/badges/tests.py
  django/badges/urls.py
  django/badges/views.py
  django/kotukotupj/settings.py
  django/kotukotupj/urls.py
  django/templates/badge_list.html
Labels: backend

#68 Feature/#66
  django/activity/views.py
  django/badges/admin.py
  django/badges/migrations/0002_auto_20230519_1932.py
  django/badges/migrations/0003_rename_badgetypecolor_badgetype.py
  django/badges/models.py
  django/badges/views.py
  django/static/admin/js/activity_add.js
  django/static/admin/js/categories_list.js
  django/static/admin/js/category_detail.js
  django/templates/activity_add.html
  django/templates/badge_list.html
  django/templates/base.html
  django/templates/category_detail.html
Labels: backend

#80 ‘カテゴリー追加・編集ページに名前重複モーダルの追加’
  django/templates/category_add.html
  django/templates/category_edit.html
Labels: front

#77 カテゴリーを作成しても、カテゴリーに紐付けて記録をしないとカテゴリーリストが表示されなかった不具合の修正
  django/categories/views.py
  django/static/admin/js/categories_list.js
Labels: front, backend

#84 実績機能の統合
  django/badges/__init__.py
  django/badges/admin.py
  django/badges/apps.py
  django/badges/migrations/0001_initial.py
  django/badges/migrations/0002_auto_20230519_1932.py
  django/badges/migrations/0003_rename_badgetypecolor_badgetype.py
  django/badges/migrations/__init__.py
  django/badges/models.py
  django/badges/tests.py
  django/badges/urls.py
  django/badges/views.py
  django/kotukotupj/settings.py
  django/kotukotupj/urls.py
  django/static/admin/js/badge_list.js
  django/templates/badge_list.html
  django/templates/base.html
Labels: front, backend

#93 activity_list.htmlの削除モーダルをバックエンドと連携
  django/categories/migrations/0002_alter_activitycategory_activity_record.py
  django/categories/models.py
  django/static/admin/js/activity_list.js
Labels: backend

#87 category_detail.htmlに削除モーダルの作成
  django/static/admin/js/category_detail.js
  django/templates/category_detail.html
Labels: front

#94 submitボタン無効化のコメントアウト
  django/static/admin/js/activity_add.js
Labels: bug

#98 [優先度中](積み上げ記録一覧画面)表示順をcreated_atへ変更
  django/activity/views.py
Labels: backend

#97 [優先度中](ホーム画面)カテゴリー削除後、グラフに削除したカテゴリーを表示しない
  django/activity/views.py
Labels: backend

#101 #67タイトル見切れ問題デスクトップのみ解決 / #89ヘッダー等の見出し統一
  django/static/admin/js/category_add.js
  django/templates/activity_add.html
  django/templates/activity_list.html
  django/templates/base.html
  django/templates/category_add.html
Labels: bug, front

#100 色の入力を不可に、ボタンを押すと枠＋サンプルを大きく
  django/static/admin/js/category_add.js
  django/templates/category_add.html
Labels: front

#122 [優先度高](実績画面)比較条件がおかしい問題の修正 と 表示がわかりやすいように変更
  django/badges/models.py
  django/badges/views.py
  django/static/admin/js/badge_list.js
Labels: backend

#128 ‘ヘッダー/ハンバーガーメニューの文言修正、ファビコンの追加’
  django/static/admin/js/existing_category.js
  django/templates/activity_add.html
  django/templates/activity_list.html
  django/templates/badge_list.html
  django/templates/base.html
  django/templates/category_add.html
  django/templates/login.html
  django/templates/regist.html
  static/admin/js/categories_list.js
Labels: front

#134 カテゴリー編集ページの色の選択の入力を削除、色枠を追加
  django/static/admin/js/category_add.js
  django/templates/category_edit.html
Labels: front

#135 カテゴリー追加と編集ページで同カテゴリ名の確認モーダルに<br>で改行を追加
  django/templates/category_add.html
  django/templates/category_edit.html
Labels: front

#148 [優先度中](カテゴリー引き継ぎモーダル)文言変更&一番最近削除したカテゴリーを引き継ぐように変更
  django/categories/urls.py
  django/categories/views.py
  django/templates/category_add.html
Labels: backend

#144 ‘入力フォームが角ばっていて不自然/「作成・戻る」ボタンのcssの調整’
  django/templates/category_add.html
  django/templates/category_edit.html
  static/admin/js/categories_list.js
Labels: front

#143 ‘積み上げ一覧の調整’
  django/static/admin/js/activity_list.js
  django/templates/activity_list.html
Labels: front
